### ISSUE TITLE
Prediction length problem

### ISSUE THREAD

**Issue by liyuzhan** [tsinghua-fib-lab/UniST#20]
Hello author, I want to change the length of pred_len from 6 to 1, but when running the code, the following problem appears, how to solve it?
Traceback (most recent call last):
  File "/data3/UniST-main/src/main.py", line 164, in <module>
    main()
  File "/data3/UniST-main/src/main.py", line 113, in main
    assert args.his_len + args.pred_len == args.seq_len
AssertionError

**Comment by YuanYuan98** [comment]
There are three parameters that define the prediction task: `his_len`, `pred_len`, and `seq_len`. Please ensure that the sum of `pred_len` and `his_len` equals `seq_len` to avoid this assertion error.
